[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  NODE_ENV = "8.9.0"

[[redirects]]
  from = "/inscricao"
  to = "https://goo.gl/forms/ZuV2aoFWjOBmRIuZ2"
  status = 302
  
[[redirects]]
  from = "/inscrever"
  to = "https://goo.gl/forms/ZuV2aoFWjOBmRIuZ2"
  status = 302

[[redirects]]
  from = "/*"
  to = "https://goo.gl/forms/ZuV2aoFWjOBmRIuZ2"
  status = 302
  
[[redirects]]
  from = "/"
  to = "https://goo.gl/forms/ZuV2aoFWjOBmRIuZ2"
  status = 302  
